### ISSUE TITLE
Unexpected exit when someone sends a message with coloring.

### ISSUE THREAD

**Issue by filipl** [osa1/tiny#1]
Currently when someone sends a message that contains a color it will immediatly exit without a message telling me why. I have not investigated more than finding out how to reproduce:

1. Start tiny
2. Connect to a server
3. Join a channel
4. From another client in the same channel, send a message with a color in it. I tested with "^C4text".
5. Have the tiny client unexpectedly exit.

Tiny built from 1558cfb

**Comment by osa1** [comment]
Thanks for reporting! This should be fixed now.
