### ISSUE TITLE
TUI feature request: grow text field vertically instead of scrolling

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#101]
Currently if I write a message long enough to not fit on the screen I have to scroll back and forth to see rest of the message. Another idea is to vertically grow the text field instead. That way I can see the whole message on screen (assuming there's vertical space on screen).

**Comment by osa1** [comment]
#125 suggests a similar thing for the tab line.

**Comment by trevarj** [comment]
Is this being worked on? I might try to take a stab at it if it's still wanted/needed.

**Comment by osa1** [comment]
@trevarj I still need it but have no time to work in it these days, so go for it. Feel free to ping me here or on IRC with questions.
