### ISSUE TITLE
Scrolling the current chat history

### ISSUE THREAD

**Issue by nifker** [osa1/tiny#106]
I think it would be useful to scroll up and down in the chat of the current session to see older messages that one missed.

**Comment by osa1** [comment]
We already provide shift-up/down and page up/down for this. Have you tried those?

**Comment by nifker** [comment]
@osa1 oh I didnt see them >.< I'm so sorry.

**Comment by osa1** [comment]
That's alright :) Make sure to read the README, it lists all of the key bindings, and there aren't too many of them.
