### ISSUE TITLE
how to setting /ignore and /notify by default?

### ISSUE THREAD

**Issue by whoizit** [osa1/tiny#118]
subject

**Comment by osa1** [comment]
This was mentioned a few times in some other tickets -- we currently doesn't support this.

Ideally I think we need a few things:

- A way to set default values of these. E.g. in the config file:

  ```
  defaults:
    ignore: true # enable ignore by default
    notify: off # disable notifications my default
  ```

- A way to set these parameters when joining, e.g.
  ```
  /join #foo -ignore -notify all
  ```

  This should join `#foo` with "ignore" on and "notify" set to "all".

- The parameters above should work in config file too, e.g.
  ```
  join:
    - '#tiny -ignore -notify all'
  ```

Not to hard to implement but I just need to allocate a few hours.

If anyone wants to contribute let me know and I can help.

**Comment by nerosnm** [comment]
Unless someone else is working on this, I think I'll take a crack at it, starting tonight, along with #217.

**Comment by osa1** [comment]
@nerosnm go for it! Let me know if you have any questions.

**Comment by trevarj** [comment]
@nerosnm anything on this? 😬

**Comment by osa1** [comment]
@trevarj it's been more than 2 months without any updates, I think this is up for grabs.

**Comment by nerosnm** [comment]
Hi, really sorry about that! This kind of slipped off my radar, I ended up not really having the bandwidth to work on it. I'll unassign myself.

**Comment by osa1** [comment]
No problem @nerosnm , thanks for the update.
