### ISSUE TITLE
Adding a rust-toolchain file

### ISSUE THREAD

**Issue by eHammarstrom** [osa1/tiny#155]
Such that cargo defaults to nightly when building tiny. Adds the possibilty to also lock the compiler version along with the already locked crates.

https://github.com/rust-lang/rustup.rs#the-toolchain-file

**Comment by osa1** [comment]
This seems like a good idea, but I couldn't make it work. As a test I added a `rust-toolchain` file with just one line: `stable`, but `cargo build` still built it with nightly even on a clean tree.

If anyone knows how to make this work a PR would be appreciated.
