### ISSUE TITLE
nixos pkg

### ISSUE THREAD

**Issue by eoli3n** [osa1/tiny#166]
Is this possible to package this for nixos ?

**Comment by osa1** [comment]
This should be possible but I don't know nix/nixos so not sure how.

**Comment by eoli3n** [comment]
I'm switching, i'll give a try, but it seems tricky

**Comment by eoli3n** [comment]
https://github.com/NixOS/nixpkgs/issues/76848

**Comment by filalex77** [comment]
@osa1 b309d1acd7f3d974f522fa55737b4df55723288f adds `Cargo.lock` to the Git tree, and is required for NixOS packaging to work. Can we get a new patch/minor release so I can package it? Thanks!

**Comment by osa1** [comment]
Sorry for late response -- I'll make a new release with #161 today.

**Comment by osa1** [comment]
I just pushed a new tag `v0.5.1`. Let me know if you need anything else.

**Comment by filalex77** [comment]
@osa1 Thanks, everything works. I'll ping you when the package is available.

**Comment by trevarj** [comment]
https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/networking/irc/tiny

Looks like this can be closed?

**Comment by osa1** [comment]
Yep, it looks like they didn't ping us after creating the package.

The version on nixpkgs is really old now, but perhaps it's up to maintainer of the package to update it.

**Comment by filalex77** [comment]
@osa1 @trevarj Yeah, I added the package, sorry for not mentioning. I'll update it soon too.
