### ISSUE TITLE
C-u keybind

### ISSUE THREAD

**Issue by eoli3n** [osa1/tiny#168]
Is this possible to add this keybind to match term behaviour ?
``C-u delete line before cursor``

**Comment by osa1** [comment]
`C-u` is currently "page up" (and `C-d` is "page down", key bindings from vim).

However given that we already support PageUp and PageDown keys maybe it'd have been better to leave `C-u` for another function.

Perhaps something to fix with #167.

**Comment by eoli3n** [comment]
Yeah, it duplicates https://github.com/osa1/tiny/issues/167
