### ISSUE TITLE
Build Failed on Manjaro, cargo 1.41.0 (626f0f40e 2019-12-03)

### ISSUE THREAD

**Issue by PulellaP** [osa1/tiny#182]
cargo install --git https://github.com/osa1/tiny
    Updating git repository `https://github.com/osa1/tiny`
  Installing tiny v0.5.1 (https://github.com/osa1/tiny#df475282)
    Updating crates.io index
  Downloaded env_logger v0.7.1
  Downloaded tempfile v3.1.0
  Downloaded time v0.1.42
  Downloaded lazy_static v1.4.0
  Downloaded unicode-width v0.1.7
  Downloaded libc v0.2.67
  Downloaded mio v0.6.21
  Downloaded tokio v0.2.13
  Downloaded termion v1.5.5
  Downloaded log v0.4.8
  Downloaded serde v1.0.104
  Downloaded futures v0.3.4
  Downloaded dirs v1.0.5
  Downloaded objekt v0.1.2
  Downloaded tokio-rustls v0.12.2
  Downloaded base64 v0.6.0
  Downloaded futures-sink v0.3.4
  Downloaded serde_yaml v0.7.5
  Downloaded futures-util v0.3.4
  Downloaded memchr v2.3.3
  Downloaded iovec v0.1.4
  Downloaded bytes v0.5.4
  Downloaded pin-project-lite v0.1.4
  Downloaded signal-hook-registry v1.2.0
  Downloaded rand v0.7.3
  Downloaded num_cpus v1.12.0
  Downloaded numtoa v0.1.0
  Downloaded tokio-macros v0.2.5
  Downloaded serde_derive v1.0.104
  Downloaded net2 v0.2.33
  Downloaded futures-io v0.3.4
  Downloaded cfg-if v0.1.10
  Downloaded rustls-native-certs v0.1.0
  Downloaded slab v0.4.2
  Downloaded futures-task v0.3.4
  Downloaded termcolor v1.1.0
  Downloaded mio-uds v0.6.7
  Downloaded fnv v1.0.6
  Downloaded futures-executor v0.3.4
  Downloaded futures-channel v0.3.4
  Downloaded regex v1.3.4
  Downloaded futures-core v0.3.4
  Downloaded remove_dir_all v0.5.2
  Downloaded humantime v1.3.0
  Downloaded atty v0.2.14
  Downloaded pin-utils v0.1.0-alpha.4
  Downloaded thread_local v1.0.1
  Downloaded aho-corasick v0.7.9
  Downloaded proc-macro-hack v0.5.11
  Downloaded linked-hash-map v0.5.2
  Downloaded dtoa v0.4.5
  Downloaded webpki v0.21.2
  Downloaded arc-swap v0.4.4
  Downloaded syn v1.0.16
  Downloaded getrandom v0.1.14
  Downloaded quote v1.0.3
  Downloaded rand_core v0.5.1
  Downloaded proc-macro2 v1.0.9
  Downloaded openssl-probe v0.1.2
  Downloaded regex-syntax v0.6.16
  Downloaded byteorder v1.3.4
  Downloaded rustls v0.16.0
  Downloaded rand_chacha v0.2.1
  Downloaded safemem v0.2.0
  Downloaded proc-macro-nested v0.1.3
  Downloaded futures-macro v0.3.4
  Downloaded quick-error v1.2.3
  Downloaded untrusted v0.7.0
  Downloaded unicode-xid v0.2.0
  Downloaded c2-chacha v0.2.3
  Downloaded base64 v0.10.1
  Downloaded ppv-lite86 v0.2.6
  Downloaded sct v0.6.0
  Downloaded yaml-rust v0.4.3
  Downloaded ring v0.16.11
  Downloaded cc v1.0.50
  Downloaded spin v0.5.2
   Compiling libc v0.2.67
   Compiling cfg-if v0.1.10
   Compiling proc-macro2 v1.0.9
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.16
   Compiling lazy_static v1.4.0
   Compiling memchr v2.3.3
   Compiling log v0.4.8
   Compiling slab v0.4.2
   Compiling futures-core v0.3.4
   Compiling cc v1.0.50
   Compiling byteorder v1.3.4
   Compiling proc-macro-nested v0.1.3
   Compiling futures-sink v0.3.4
   Compiling spin v0.5.2
   Compiling getrandom v0.1.14
   Compiling untrusted v0.7.0
   Compiling arc-swap v0.4.4
   Compiling futures-io v0.3.4
   Compiling pin-utils v0.1.0-alpha.4
   Compiling futures-task v0.3.4
   Compiling bytes v0.5.4
   Compiling ppv-lite86 v0.2.6
   Compiling pin-project-lite v0.1.4
   Compiling regex-syntax v0.6.16
   Compiling quick-error v1.2.3
   Compiling fnv v1.0.6
   Compiling objekt v0.1.2
   Compiling termcolor v1.1.0
   Compiling serde v1.0.104
   Compiling numtoa v0.1.0
   Compiling linked-hash-map v0.5.2
   Compiling openssl-probe v0.1.2
   Compiling remove_dir_all v0.5.2
   Compiling unicode-width v0.1.7
   Compiling safemem v0.2.0
   Compiling dtoa v0.4.5
   Compiling libtiny_wire v0.1.0 (https://github.com/osa1/tiny#df475282)
   Compiling thread_local v1.0.1
   Compiling futures-channel v0.3.4
   Compiling humantime v1.3.0
   Compiling yaml-rust v0.4.3
   Compiling c2-chacha v0.2.3
   Compiling aho-corasick v0.7.9
   Compiling quote v1.0.3
   Compiling base64 v0.10.1
   Compiling base64 v0.6.0
   Compiling net2 v0.2.33
   Compiling iovec v0.1.4
   Compiling signal-hook-registry v1.2.0
   Compiling num_cpus v1.12.0
   Compiling time v0.1.42
   Compiling atty v0.2.14
   Compiling termion v1.5.5
   Compiling dirs v1.0.5
   Compiling regex v1.3.4
   Compiling mio v0.6.21
   Compiling rand_core v0.5.1
   Compiling libtiny_ui v0.1.0 (https://github.com/osa1/tiny#df475282)
   Compiling termbox_simple v0.2.3 (https://github.com/osa1/tiny#df475282)
   Compiling ring v0.16.11
   Compiling rand_chacha v0.2.1
   Compiling mio-uds v0.6.7
   Compiling env_logger v0.7.1
   Compiling rand v0.7.3
   Compiling libtiny_logger v0.1.0 (https://github.com/osa1/tiny#df475282)
   Compiling tempfile v3.1.0
   Compiling webpki v0.21.2
   Compiling sct v0.6.0
   Compiling rustls v0.16.0
   Compiling rustls-native-certs v0.1.0
   Compiling proc-macro-hack v0.5.11
   Compiling tokio-macros v0.2.5
   Compiling serde_derive v1.0.104
   Compiling futures-macro v0.3.4
   Compiling tokio v0.2.13
   Compiling futures-util v0.3.4
   Compiling tokio-rustls v0.12.2
   Compiling futures-executor v0.3.4
   Compiling futures v0.3.4
   Compiling term_input v0.1.5 (https://github.com/osa1/tiny#df475282)
   Compiling libtiny_client v0.1.0 (https://github.com/osa1/tiny#df475282)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/pasquale/.cargo/git/checkouts/tiny-052ac3f82f110ac6/df47528/libtiny_client/src/lib.rs:2:1
  |
2 | #![feature(test)]
  | ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `libtiny_client`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tiny v0.5.1 (https://github.com/osa1/tiny#df475282)`, intermediate artifacts can be found at `/tmp/cargo-installoeQPa7`

Caused by:
  build failed

**Comment by osa1** [comment]
You need to use a nightly compiler, see README for more details.

**Comment by PulellaP** [comment]
I already figured it out thanks though.
