### ISSUE TITLE
Tiny panics without visible message when `nicks` is an empty list

### ISSUE THREAD

**Issue by e00E** [osa1/tiny#184]
Default configuration but `nicks` is `[]` for freenode.

Then run `tiny`.  A message flashes on the terminal but disappears immediately before I can read it. By redirecting `stderr` to a file I can recover this:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 25, kind: Other, message: "Inappropriate ioctl for device" }', libtiny_tui/src/tui.rs:69:18

**Comment by trevarj** [comment]
If you need a way to get around this, the following works:
```
      nicks:
        -
```

**Comment by osa1** [comment]
Thanks for reporting. So first of all we should improve error reporting. Printing to stderr is not helpful in a TUI app. In the worst case I think we could redirect stderr to a file, but I think ideally all errors would be shown in tiny. Not sure if that's easily possible.

Secondly I think we should improve checking user errors in config files.
