### ISSUE TITLE
Allow naming servers to give them a better display name

### ISSUE THREAD

**Issue by e00E** [osa1/tiny#186]
Currently the address of the server is used to display the server tab. For some servers this can be unhelpful (ip address) or too long (very long domain name). I would like to be able to give my servers a helpful name in the config. This name would be used instead.

**Comment by trevarj** [comment]
Implementing feature here:
https://github.com/osa1/tiny/pull/188

**Comment by osa1** [comment]
This is now implemented. Just add an `alias` field to your server configuration. Example:

```
    - addr: chat.freenode.net
      alias: freenode
      ...
```

Here in the tab line you'll see `freenode` instead of `chat.freenode.net` as before.

**Comment by e00E** [comment]
Thank you osa and trevarj.
