### ISSUE TITLE
Sort out the variant size difference in Stream when using rustls

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#189]
When I run clippy with rustls I get this warning:

```
libtiny_client git:(master) $ cargo clippy --no-default-features --features="tls-rustls"
    Checking libtiny_client v0.1.0 (/home/omer/rust/tiny/libtiny_client)
warning: large size difference between variants
  --> libtiny_client/src/stream.rs:35:5
   |
35 |     TlsStream(TlsStream<TcpStream>),
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this variant is 1280 bytes
   |
   = note: `#[warn(clippy::large_enum_variant)]` on by default
note: and the second-largest variant is 56 bytes:
  --> libtiny_client/src/stream.rs:34:5
   |
34 |     TcpStream(TcpStream),
   |     ^^^^^^^^^^^^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant
help: consider boxing the large fields to reduce the total size of the enum
   |
35 |     TlsStream(Box<TlsStream<TcpStream>>),
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: 1 warning emitted
```

1280 bytes vs. 56 bytes is quite a difference and we should fix this warning.

No such warning is given when using native-tls so perhaps we don't need to box always, we can only box when using rustls.

This warning is new, it'd be good to which commit in `tokio-rustls` or `rustls` caused this.

**Comment by trevarj** [comment]
https://github.com/rust-lang/rust-clippy/commit/69c3e9c90f9a7731dcfe129b10e55e440ee6f484

Is this it?

**Comment by osa1** [comment]
That only changed the lint warning message format, I think the warning is generated after 87ecc9ea04a3ad7cd0ac248b2a955908af04669e because of a change in a dependency.

**Comment by osa1** [comment]
Hmm, if I revert 87ecc9e I get the same warning, so I guess dependency bump was not the reason for this. Perhaps this warning has always been there (since we've added `rustls` support) but I missed it somehow?
