### ISSUE TITLE
Unable to start tiny with error: UnsupportedTerminal

### ISSUE THREAD

**Issue by Velfolt** [osa1/tiny#19]
I'm using alacritty and zsh in Ubuntu 16.04. When starting tiny after it has first generated its config files the following output is produced.

```
tiny [master] % RUST_BACKTRACE=1 tiny
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedTerminal', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:71
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:396
             at /checkout/src/libstd/panicking.rs:610
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:571
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
   5: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:497
   6: core::result::unwrap_failed
   7: tiny::run
   8: main
   9: __libc_start_main
  10: _start
```

**Comment by osa1** [comment]
What does  `echo $TERM` say? What happens if you run `export TERM=xterm-256color` before running tiny?

**Comment by Velfolt** [comment]
I have tried in two different terminal emulators:

In Konsole `echo $TERM` returns `xterm` and does not work with `export TERM=xterm-256color`.
In Alacritty with zsh and running inside tmux `echo $TERM` returns `screen` and does not work with `export TERM=xterm-256color`.

Maybe zsh is the issue?

**Comment by osa1** [comment]
I'm confused. I just tried with latest alacritty (built from git repo) with zsh and it worked fine.

What do you mean by "does not work"? What's not working when you run `TERM=xterm-256color tiny` ?

**Comment by Velfolt** [comment]
Sorry about not giving the error message. It's the same as before.

```
tiny [master] % TERM=xterm-256color tiny
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedTerminal', /checkout/src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by osa1** [comment]
Do you have this file on your system:

```
$ file /usr/share/terminfo/x/xterm-256color 
/usr/share/terminfo/x/xterm-256color: Compiled terminfo entry
```

?

**Comment by Velfolt** [comment]
I do not!

**Comment by osa1** [comment]
Hmm.. that probably explains. What distro are you using? Do you have a `terminfo` package in your distro's package manager?

The code that's failing in your case is the function that tries to learn about your terminal. It first reads `$TERM`, then tries to find terminfo file for `$TERM`. I think in your case you don't have terminfo files so that part fails.

Could you install the terminfo files using your distro's package manager and let me know if that fixes it?

**Comment by osa1** [comment]
I think 08b43da0c08284db46d0d947e6e6f0b9a8403c0d is responsible for this. Fix should be as easy as reverting it.

**Comment by osa1** [comment]
I uploaded a new version on crates.io, could you try updating tiny and let me know if that fixes this? `cargo install tiny --force` should work.

**Comment by Velfolt** [comment]
I'm using Kubuntu 16.04. 

And yes, that solved it!! Great work! :D

**Comment by osa1** [comment]
Yay!
