### ISSUE TITLE
Too many unwrap()s while parsing config

### ISSUE THREAD

**Issue by joek13** [osa1/tiny#2]
Hey, I was taking a look at this project and it seems pretty cool so far. I was setting up Tiny on my machine, but made an error in the configuration. `read_config` should really return `Result<Option<(Vec<Server>, Defaults, String), ConfigError>` where ConfigError can explain what went wrong.

Simply panicking when there is an issue is not only ugly to the user, but it's extremely unhelpful to contributors or people attempting to fix the issue. I had to enable the backtrace and hunt down which value was unwrapping wrongly because there's no error handling.

Another small note: you may want to consider a type alias (`type Config = (Vec<Server>, Defaults, String`) or even defining a Config struct with named fields. It makes your code a little bit more readable and you can use a library like `serde_derive` to easily serialize/deserialize your Config struct.

**Comment by osa1** [comment]
Hey, thanks for the report. This is indeed very annoying, even I were confused by this several times after I temporarily enabled/disabled some auto cmds and introduced syntax errors while doing this. Would you be interested in implementing this yourself and send a PR? Otherwise I can take care of this sometime this week probably.

**Comment by joek13** [comment]
Yeah, I'm getting to work on refactoring your config parser. Forked it already.

I'll submit a PR soon.

**Comment by joek13** [comment]
See #5 for the pull request.

Unrelated, but I don't think it warrants its own issue: You should probably be using something like `rust-fmt` to format your code. It's a utility that formats code according to the Rust style guidelines so that contributors don't have to worry about messing up another crate's style. You can configure it to activate on write with many editors.
