### ISSUE TITLE
Add index based tab switching

### ISSUE THREAD

**Issue by DirectorX** [osa1/tiny#20]
`C-n`/`C-p` for next/previous tab and `C-{0,9}` for index based switching.

**Comment by osa1** [comment]
I'm afraid we can't use `C-{0,9}`, on xterm-compatible terminals `C-3` generates same byte sequence with  `ESC`, `C-9` generates the same sequence with backspace etc.

But I think we can use `alt-{0,9}`, how does that sound?

I'm considering making `alt-9` "switch to last tab", similar to how it behaves in chrome.

**Comment by DirectorX** [comment]
`alt-{0,9}` is ok

**Comment by osa1** [comment]
This is just a `cargo install tiny --force` away. Enjoy!
