### ISSUE TITLE
Long, spaceless messages get cut off

### ISSUE THREAD

**Issue by trevarj** [osa1/tiny#202]
Long messages that don't have enough spaces to line wrap get truncated.

I believe this is due to the `draw()` in `line.rs` and how it handles when there is no whitespace to split on.
```
                    // Not possible to split. Need to make sure we don't render out
                    // of bounds.
                    if col - pos_x < width {
                        if line >= first_line {
                            tb.change_cell(col, pos_y + line, char, sty.fg, sty.bg);
                        }
                        col += 1;
                    }
```

This isn't a huge problem. Personally, I would just resize the window and hope that the message/link can all fit, but it's probably a pain for people using a tiling window manager...

Wide view:
![image](https://user-images.githubusercontent.com/5448324/83335246-26622280-a2b4-11ea-9a34-e0f347a91436.png)
Compact view:
![image](https://user-images.githubusercontent.com/5448324/83335256-337f1180-a2b4-11ea-87d7-71c298c95373.png)

Tested on master

**Comment by osa1** [comment]
Thanks for reporting. I thought I handled this, but apparently not. I think this is pretty bad as it can be misleading. For example, if someone pasted a long link and the window width is small, the link will cut off and when you copy you'll only copy the prefix.

We should split the line at the last visible character when this happens.

**Comment by trevarj** [comment]
> We should split the line at the last visible character when this happens. 

I'm afraid this will be a messy add on to how it's being done now. Similar to the text input problem with calculating the number of lines...
