### ISSUE TITLE
Write message from `Global` to the server window

### ISSUE THREAD

**Issue by DirectorX** [osa1/tiny#21]
message from `Global` should be received in the server window.

![](https://i.gyazo.com/7378b7a560fbae31a08218da71eb746e.png)

**Comment by osa1** [comment]
It seems to me that `Global` is not a special name, and could be used by users in other servers. Maybe we can add a new field to `servers` field in `.tinyrc.yml` to specify which nicks are bots, and should be shown in the server tab instead of in new tabs. How does that sound?

**Comment by DirectorX** [comment]
You are right, I think this kind of messages have something different from normal messages. I will look in to it when I have time. Also we should put messages from `*serv` in the main buffer for example messages from  HostServ etc..

**Comment by DirectorX** [comment]
Hi  @osa1
Here a sample of raw global messages
```
:Global!services@p2p-network.net NOTICE void :[.Logon News. - Dec 20 15:31:59 2009 CST] We now have to pay approximately $300 a month to maintain our servers. Any donation would be welcome and can be done at http://www.p2p-network.net/ or directly to donate@p2p-network.net via PayPal. Thanks
:Global!services@p2p-network.net NOTICE void :[.Random News. - Dec 30 08:51:05 2006 CST] For users who do NOT want to see network messages/announcements please set mode -w ( in mirc: //mode $me -w )
```

**Comment by osa1** [comment]
One of the servers I connect these days also use `Global` for announcements, it's very annoying. I just checked and somehow konversation shows these messages in the server tab, I wonder how it does this. I'll check the source code.

**Comment by FreeFull** [comment]
Irssi sends all `NOTICE`s to the server tab if there is no corresponding query window open.

**Comment by osa1** [comment]
Hmm that's a good idea, we should probably do the same. I just checked and it seems like `NickServ` messages are also `NOTICE`s so we implement this we can get rid of this special case for `NickServ` messages.

**Comment by osa1** [comment]
This worked out nicely. Thanks for the idea @FreeFull.
