### ISSUE TITLE
Logger fails to create log file when channel name includes forward slash

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#214]
@Kabouik reports in #211

> I think the issue might be related to Gitter rooms being formatted with a slash in their name, which must conflict with the way tiny sets filenames for logs. You can see above in my configuration file that the channel I wanted to join on irc.gitter.im was "#jarun/nnn". If this is really the cause, then perhaps an acceptable workaround would be to replace / with another character when creating new log files, such as -?

In other words when the channel name contains `/` logger fails to create the log
file and reports this in "mentions" tab:

```
Logger error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Two TODOs:

- [x] The error message should show the file path
- [ ] We should handle channel names with `/`s in them (as far as I can see RFC 2812 allows this)

**Comment by osa1** [comment]
@Kabouik thanks again for reporting this. Please let me know if you encounter any other problems.

**Comment by Kabouik** [comment]
Thanks for the quick fix. This solved the issue on my computer, but for some reason the issue persists on my SailfishOS device. `tiny 0.5.1 (4af06df)`, installed with native tls and `--force`. The issue is probably on my end since it works fine on the computer, but both are using the same `config.yaml` so I don't know where to start troubleshooting yet.

**Comment by osa1** [comment]
@Kabouik what exactly does the error message say? I updated the error logging today so you should see a more detailed error message that also show the problematic file path.

**Comment by Kabouik** [comment]
Actually that is what surprised me, I should have said that in my first message: the error is the same as the one posted here, which is why I double checked the version to make sure it included your fix. That's also why I believe the issue may be on my end only.

**Comment by osa1** [comment]
It seems like you need to recompile and reinstall tiny. Make sure `tiny --version` prints `tiny 0.5.1 (4af06df)`.

**Comment by Kabouik** [comment]
It does.

**Comment by osa1** [comment]
What does the error message say exactly?

**Comment by Kabouik** [comment]
` ` `
Can't create logger: on such file or directory (os error2)
```

**Comment by osa1** [comment]
That can't be the actual message. If you paste the actual message I'll try to help.

**Comment by Kabouik** [comment]
![Screenshot_20200621_001](https://user-images.githubusercontent.com/7107523/85232651-0a9ff700-b3f0-11ea-803c-703098ee2b98.png)

**Comment by osa1** [comment]
@Kabouik thanks.. so the problem is logger can't create the log directory. I slightly improved the error message in b7dfd9c so you'll now see the path it failed to create. I think the most common reason for this is you have `/foo/bar/baz` as your log directory but `/foo/bar` doesn't exist. We currently don't create parent directory, we assume that it exists. Perhaps we should change this to create all directories. Any opinions on that? cc @trevarj

**Comment by trevarj** [comment]
Yeah, I think using `create_dir_add` would be better.

**Comment by osa1** [comment]
OK, done.

**Comment by Kabouik** [comment]
I am sorry to say that I realized now (thanks to the improved error message in b7dfd9c) that the issue on the SailfishOS device was probably due to me synchronizing the config file between the two devices after the forward slash fix. I didn't notice that the path to the log files was written in the form of `/home/user/` instead of `$HOME`, which of course caused issues due to different user names between the two machines. How dumb. I'm sorry if I wasted your time. The improved error reports will surely be useful though, and I hope that b640776 is stilll a progress for `tiny` regardless.

**Comment by osa1** [comment]
No worries -- as you say these improvements will be helpful to others. They could've even helped you by showing the full path as you'd realize the mistake there.

Btw, we have a WIP PR #171 to support `$HOME` in log dir path. We couldn't find a good design so it's on hold currently. If you have any opinions on that let us know in the PR.

**Comment by Kabouik** [comment]
Uh, the master version doesn't have that already? Because that's what I have put in my `config.yml` since my message above, and it solved the issue for me:

``` 
# Where to put log files
log_dir: '$HOME/.config/tiny/tiny_logs'
```

**Comment by osa1** [comment]
@Kabouik If you use `$HOME` in your log dir path a directory named `$HOME` will be created, so for example if you run tiny in `/home/user/tiny` you'll find your logs in `/home/user/tiny/$HOME` :-)

Perhaps we should prioritize #171.

**Comment by Kabouik** [comment]
Uh, you're right, confirmed! With `log_dir: '$HOME/.config/tiny/tiny_logs'` in my configuration, logs are stored in `ls /home/kabouik/\$HOME/.config/tiny/tiny_logs/`.

But then if `tiny` automatically created the `$HOME` directory in `/home/kabouik`, can't I just use `log_dir: `.config/tiny/tiny_logs' and have it automatically created in my real `$HOME` regardless of the username?

**Comment by osa1** [comment]
> But then if tiny automatically created the $HOME directory in /home/kabouik, can't I just use log_dir: .config/tiny/tiny_logs and have it automatically created in my real $HOME regardless of the username?

This would work if you make sure you run tiny in `$HOME`, because `.config/tiny/tiny_logs` is relative to the current working directory. Perhaps you could write a wrapper script that changes the working directory to `$HOME` first and then runs tiny.

**Comment by Kabouik** [comment]
I see. I ran `tiny` from `~/` indeed. I can do a script or alias `tiny` to `cd ~/ && tiny` for now (or just put the real user names in my config files on different machines), but for the long term, support for `$HOME` or `~/` will be great!
