### ISSUE TITLE
Prefix without '!' assumed to be a server

### ISSUE THREAD

**Issue by kennylevinsen** [osa1/tiny#247]
RFC2812 defines prefix as follows:
```
prefix     =  servername / ( nickname [ [ "!" user ] "@" host ] )
```

By this syntax, a prefix can be proven to be a nick if it contains either '!' or '@'. Otherwise, it is ambigious.

However, libtiny_wire treats any prefix not containing a '!' as a server name, and tiny replaces server names with the connection connection server. This leads to situations where all history-playback from a bouncer like soju ends up replacing all nicks with the server name.

For non-zero prefixes, a simple `struct { name, user, host }` would probably make the most sense, removing the distinction. Empty prefixes could then be communicated separately, either through an option or an empty Server enum value, for when tiny needs to add the server name itself in the UI.

**Comment by osa1** [comment]
Thanks for reporting. You're right that we don't handle the ambiguous case correctly, instead we assume that the sender is a server.

I think we could improve the situation by searching for '.' and '-' characters in the prefix when there isn't a '!' or '@', because nicks can't have those characters. I think this would solve the problem when connecting to soju, right?

If the prefix doesn't have those characters and doesn't have '!' or '@' then there will still be ambiguity, which I'm not sure how to handle best. Perhaps in that case assuming server as we do today is fine as I never seen this become a problem in years of use until this bug report.

**Comment by osa1** [comment]
I tried to run soju locally to see the problem myself and whether my proposed fix above will work, but I can't follow the instructions in the README:

```
$ go run ./cmd/sojuctl create-user soju-osa1 -admin
warning: GOPATH set to GOROOT (/home/omer/go) has no effect
go: downloading golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a
go: downloading github.com/google/shlex v0.0.0-20191202100458-e7afc7fbc510
go: downloading gopkg.in/irc.v3 v3.1.3
go: downloading github.com/emersion/go-sasl v0.0.0-20200509203442-7bfe0ed36a21
go: downloading nhooyr.io/websocket v1.8.6
go: downloading github.com/mattn/go-sqlite3 v1.14.1
go: downloading github.com/klauspost/compress v1.10.11
go: downloading golang.org/x/sys v0.0.0-20200824131525-c12d262b63d8
# runtime/internal/atomic
../../go/src/runtime/internal/atomic/atomic_amd64x.go:13:6: Load redeclared in this block
        previous declaration at ../../go/src/runtime/internal/atomic/atomic_amd64.go:16:24
../../go/src/runtime/internal/atomic/atomic_amd64x.go:19:6: Loadp redeclared in this block
        previous declaration at ../../go/src/runtime/internal/atomic/atomic_amd64.go:22:32
../../go/src/runtime/internal/atomic/atomic_amd64x.go:25:6: Load64 redeclared in this block
        previous declaration at ../../go/src/runtime/internal/atomic/atomic_amd64.go:28:26
../../go/src/runtime/internal/atomic/atomic_amd64x.go:30:6: Xadd redeclared in this block
        previous declaration at ../../go/src/runtime/internal/atomic/atomic_amd64.go:39:37
../../go/src/runtime/internal/atomic/atomic_amd64x.go:33:6: Xadd64 redeclared in this block
        previous declaration at ../../go/src/runtime/internal/atomic/atomic_amd64.go:42:39
../../go/src/runtime/internal/atomic/atomic_amd64x.go:36:6: Xadduintptr redeclared in this block
        previous declaration at ../../go/src/runtime/internal/atomic/atomic_amd64.go:45:47
../../go/src/runtime/internal/atomic/atomic_amd64x.go:39:6: Xchg redeclared in this block
        previous declaration at ../../go/src/runtime/internal/atomic/atomic_amd64.go:48:36
../../go/src/runtime/internal/atomic/atomic_amd64x.go:42:6: Xchg64 redeclared in this block
        previous declaration at ../../go/src/runtime/internal/atomic/atomic_amd64.go:51:38
../../go/src/runtime/internal/atomic/atomic_amd64x.go:45:6: Xchguintptr redeclared in this block
        previous declaration at ../../go/src/runtime/internal/atomic/atomic_amd64.go:54:45
../../go/src/runtime/internal/atomic/atomic_amd64x.go:48:6: And8 redeclared in this block
        previous declaration at ../../go/src/runtime/internal/atomic/atomic_amd64.go:63:27
../../go/src/runtime/internal/atomic/atomic_amd64x.go:48:6: too many errors
```

I'll still submit a PR, it'd be helpful if you could let me know if it fixes the issue.

**Comment by kennylevinsen** [comment]
> Thanks for reporting.

Thanks for authoring. :)

> I think we could improve the situation by searching for '.' and '-' characters in the prefix when there isn't a '!' or '@', because nicks can't have those characters. I think this would solve the problem when connecting to soju, rig

It would solve my instance of the problem, but it won't fix the bug. As a dumb example, "localhost" is a valid server hostname.

> If the prefix doesn't have those characters and doesn't have '!' or '@' then there will still be ambiguity, which I'm not sure how to handle best. 

There is no mechanism to distinguish prefix type, and any attempt will break in valid IRC use-cases as can be seen here, so we should not try to do that. I suppose one could compare the content to the known server name if detection is necessary later, but I'd recommend against doing that if it's not needed.

`tiny` prints the prefix the same way for both assumed servers and assumed users. The problem is that it is replacing the sent name with its own name for assumed servers. Instead, it should just always print the actual name, and only fill in the server name if the prefix was missing.

This is what my local quickfix does, and I see no regressions - it just stops replacing all nicks in bouncer history with the server name. This would be cleaner implemented as an `Option` of `struct Name { name: String; user, host: Option<String>; }` or something similar.

> I never seen this become a problem in years of use until this bug report.

Well, it's a matter of what servers you connect to. Soju is a newer bouncer, but as long as it's following the spec, things are supposed to work, and from what I can tell this prefix use is entirely valid.

**Comment by osa1** [comment]
I'm updating my fix but just to make sure I understand the problem correctly, in your original message

> tiny replaces server names with the connection connection server. This leads to situations where all history-playback from a bouncer like soju ends up replacing all nicks with the server name.

I don't think we replace server names. I think what you mean is when the sender looks like a server we show the message in the server tab, so with your bouncer all messages end up in the server tab, right?

**Comment by osa1** [comment]
@kennylevinsen #249 should fix this, could you confirm? I'd do it myself but I can't run the bouncer (see my comment in the PR).

**Comment by kennylevinsen** [comment]
> I don't think we replace server names. I think what you mean is when the sender looks like a server we show the message in the server tab, so with your bouncer all messages end up in the server tab, right?

https://github.com/osa1/tiny/blob/7490bede5d7a8d9f2313ed7fe86215e4dadac391/tiny/src/conn.rs#L148.

Any prefix identified as a "Server" is ignored and replaced by the conn server string. This is how the problem manifested itself.

> @kennylevinsen #249 should fix this, could you confirm? I'd do it myself but I can't run the bouncer (see my comment in the PR).

Tried it, and it's not quite there: Nicks with hyphens were still replaced with server names, as the code assumes hyphens can only be in server names.

To be honest, I don't understand what value the Server and User types bring when the ambiguity is thrown into the mix. E.g., anyone needing a Server will need to check both Server and Ambiguous, which are identical types. There's a little value to a dedicated User as it carries the additional params, but I suspect that a type named in such way is just going to cause misinterpretation...

**Comment by osa1** [comment]
Thanks @kennylevinsen. I udpated the code you showed above, it no longer overrides the server name (no idea why that was done).

Hypens should also be handled correctly now.

> To be honest, I don't understand what value the Server and User types bring when the ambiguity is thrown into the mix. E.g., anyone needing a Server will need to check both Server and Ambiguous, which are identical types. There's a little value to a dedicated User as it carries the additional params, but I suspect that a type named in such way is just going to cause misinterpretation...

I tried to document this in the `Pfx` type's documentation in the PR.

**Comment by kennylevinsen** [comment]
Looks like the user-side of things works as they should now.
