### ISSUE TITLE
Channels/nicks need to be case-folded on match

### ISSUE THREAD

**Issue by kennylevinsen** [osa1/tiny#248]
A PRIVMSG received for "#MyChan" and #mychan" must go to the same buffer, as if they were both sent to "#mychan".

This is necessary due to servers' performing this case folding when reading such messages. Note that IRC only does ASCII case-folding, not Unicode case-folding. Unicode case-folding will *not* work. See the discussion here: https://todo.sr.ht/~emersion/soju/52.

**Comment by osa1** [comment]
Thanks for reporting. I'm not sure that this is a problem. We only create a channel tab based on the server's `JOIN` response. For example, if I send `JOIN #MyChan` to irc.oftc.net this is the `JOIN` response I get from the server:

```
:osa1_!~osa1@... JOIN :#MyChan
```

Note that the channel name is not case folded. We just create a channel with the name used in the server's response.

Here's something I tried: I connect to irc.oftc.net in two clients (both tiny), join #mychan first with one, and then join #MyChan with the other. If I do that than the second client gets this response:

```
:osa1__!~osa1@... :#mychan
```

Note that this one is case-folded.

In all cases I end up connecting to the right channel and both clients were able to communicate in the same channel. I also tried first creating `MyChan` and then joining `mychan`, and that also worked as expected.

So I think we handle this case correctly by waiting for server response before creating a tab. Am I missing anything?

**Comment by kennylevinsen** [comment]
Sorry, I should have provided some more data at the beginning.

Reproduction:
1. Connect tiny, and KiwiIRC to irc.geekshed.net
2. Create a channel, e.g. "tinytestchan", and join from both clients
3. From KiwiIRC: `/privmsg #TinyTestChan hi`
4. Observe that tiny creates a new buffer named #TinyTestChan where this message is received
5. Write a message in both buffers in tiny
6. Observe that KiwiIRC receives both messages in the same buffer

Conclusions:
- The IRC server considers someone tinytestchan and TinyTestChan to be the same channel.
- The IRC server forwards the casing provided by the client, leading to PRIVMSG's for both tinytestchan and TinyTestChan.
- Kiwi normalizes this correctly, while tiny creates new buffers with each containing only part of the channel conversation.

To fix this, tiny must case-fold channel names during any comparisons. Note that unicode folding *must not* be used. I believe this also applies to nicks, but I have not looked into the detals for that (and as I assume it only affects mentions, it's also less important).

**Comment by osa1** [comment]
Thanks for the example. You're right that this is a bug in tiny. RFC 2812 clearly states in section 1.3 that channel names are case insensitive.

IRC is an ASCII-based protocol so I'd expect unicode characters in channel and nick names to be rejected, but it seems like most servers (e.g. geekshed, OFTC) accept unicode in channel names but not in nicks.. sigh.
