### ISSUE TITLE
Messages with colons appear mangled

### ISSUE THREAD

**Issue by kennylevinsen** [osa1/tiny#251]
If a message starts with an unbroken sequence of characters that include a colon, then everything up to and including the colon is removed. URLs have their scheme removed ("https://github.com/" -> "//github.com/"), and nick mentions disappear ("kennylevinsen:" -> "").

The problem doe snot seem to appear if the sequence is broken by a space. I assume this is a case of IRC command argument splitting gone wrong.

**Comment by osa1** [comment]
Thanks for reporting. I think this should be fixed now. Please feel free to reopen if it's not fixed.
