### ISSUE TITLE
/who, /whois, /whowas support?

### ISSUE THREAD

**Issue by jedahan** [osa1/tiny#264]
Would be nice to support these commands if possible

**Comment by osa1** [comment]
You can use these commands today by sending the IRC commands in the server tab. For example, if I send `WHOIS osa1` in a server tab I get something like

```
coulomb.oftc.net: osa1 osa1 ~osa1 178.233.177.154 * omer
coulomb.oftc.net: osa1 osa1 #openjdk #tiny #llvm
coulomb.oftc.net: osa1 osa1 coulomb.oftc.net London, United Kingdom
coulomb.oftc.net: osa1 osa1 user has identified and verified with services
coulomb.oftc.net: osa1 osa1 178.233.177.154 actually using host
coulomb.oftc.net: osa1 osa1 is connected via SSL (secure link)
coulomb.oftc.net: osa1 osa1 20 1605161424 seconds idle, signon time
coulomb.oftc.net: osa1 osa1 End of /WHOIS list.
```

Same for other commands.

Do you still think we need special support from tiny for these commands?

**Comment by jedahan** [comment]
hmm maybe not 'special support' but perhaps a message explaining this to people who have gotten into bad habits?
