### ISSUE TITLE
notifications not working with mako on swaywm

### ISSUE THREAD

**Issue by salkin-mada** [osa1/tiny#267]
I am not receiving any notifications from `tiny`
`/notify` return `Notifications enabled for mentions` but when someone mentions my `nick``nothing happens. Just to double check i tried `cargo run --example simple` from the `notify-rust` crate and surely i am receiving the silly `Critical Error - Just kidding, this is just the notificationexample.` notification via `mako`

**Comment by osa1** [comment]
Are you using a libdbus-enabled build? If you're using a pre-built binary from the releases page make sure to use one with "libdbus" in its name. If you're building from the source you need to add `--features desktop-notifications`. See also [README](https://github.com/osa1/tiny#installation) for installation instructions.

**Comment by salkin-mada** [comment]
I am using the `tiny-irc-client` aur package - i am on Arch Linux 5.9.1-rt20
the `tiny` version provided with this `aur` is `0.7.0`
and the PKGBUILD file specifies `libdbus` as an dependency.

**Comment by salkin-mada** [comment]
aha! 

the PKGBUILD specifies the source as follows:
```
pkgver=0.7.0
source=("https://github.com/osa1/tiny/archive/v${pkgver}.tar.gz")
```
and no `--features desktop-notifications` is added to the build instructions.
```
build() {
  cd "${srcdir}/tiny-${pkgver}"
  rustup override set nightly
  cargo build --release --locked
} 
```
I will inform the package maintainer.

+++ also, it seems there is no need of using `nighly` for `rustc 1.47.0`

**Comment by osa1** [comment]
Perfect, thanks for debugging and letting the maintainer know.

You are right that we no longer need nightly rustc.

**Comment by eoli3n** [comment]
I use ``tiny-irc-client-git`` aur package on Archlinux.
When I trigger the build I edit build command to add ``--features desktop-notifications``
```
build() {
           #  Installs the Rust nightly toolchain to a temporary
           #  directory. If you already have the toolchain installed,
           #  e.g. via the script at https://rustup.rs/ or another
           #  package, you can remove the rust-nightly dependancy and
           #  comment out the following three commands.

          mkdir nightly
          export RUSTUP_HOME=$(pwd)/nightly
          rustup toolchain install nightly

          # build tiny
          cd tiny
          cargo +nightly build --release --features desktop-notifications
}
```
get 
```
mkdir: impossible to create directory « nightly »: File exists
```
restart build and edit mkdir command 
```
mkdir -p nightly
```
Then build gave
```
==> Lancement de build()…
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.50.0-nightly (825637983 2020-11-18)

error: --features is not allowed in the root of a virtual workspace
note: while this was previously accepted, it didn't actually do anything
help: change the current directory to the package directory, or use the --manifest-path flag to the path of the package
```

**Comment by osa1** [comment]
So the first error is because this directory does not exist: `$(pwd)/nightly`

The second error is because you're using `cargo build` in a workspace with many crates and as far as I know you can't use `--features` with that. You have two options:

- Somehow use `cargo install` as shown in the [README](https://github.com/osa1/tiny#installation).
- Run `cargo build` in `tiny/` directory, like `cd tiny; cargo build ...`. You already have `cd tiny` but I believe that just enters the cloned git repo, you need `cd tiny/tiny` for `cargo build` to work.

Also, you no longer need nightly rustc for tiny so you can remove `+nightly`.

I don't use Arch so I can't test this myself.

**Comment by eoli3n** [comment]
> So the first error is because this directory does not exist: $(pwd)/nightly

That because it does already exist, that's why I added ``-p`` to mkdir.
Built with
```
build() {
          mkdir -p nightly
          export RUSTUP_HOME=$(pwd)/nightly
          rustup toolchain install nightly
          
          # build tiny
          cd tiny
          cargo install --path tiny --features=desktop-notifications
}
```

It works well with feature enabled

![2020-11-19T13:07:26,582841730+01:00](https://user-images.githubusercontent.com/14223657/99664455-7ef6c900-2a68-11eb-9cee-4e9c2d5a1618.png)


---
NOTE:

Procedure to test on archlinux in a container:
1. Install docker or podman package on your distro (podman is better, it doesn't need a daemon like dockerd to work). All args are exactly same, just replace ``podman`` with ``docker`` in command if you want to.

2. Run an archlinux container, and mount tiny config file. If image doesn't exist locally yet, it will pull it automatically.
```
$ podman run --volume ~/.config/tiny:/home/user/.config/tiny --rm -it archlinux /bin/bash
```

3. Prepare container
```
# In container, upgrade and install deps
$ pacman -Syu git fakeroot sudo binutils nano gcc cmake --noconfirm

# Create a new sudo user
$ useradd -m user && passwd user && usermod -aG wheel user
$ echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
```
4. Connect with user, build and install tiny
```
# Connect with user
$ su - user
$ git clone https://aur.archlinux.org/trizen.git && cd trizen && makepkg -si --noconfirm

# Install aur package, which automate the whole build and install process and give ability to edit build script
# Edit will use nano by default
$ trizen -S tiny-irc-client-git --noconfirm
# It will prompt for editing files, you will figure it out at this point
```
When you exit the container, everything is lose.
TODO: how to connect to Xorg or Wayland, I will add this a bit later

**Comment by eoli3n** [comment]
I can't build with ``cargo install --path tiny --features=desktop-notifications`` in container. I wanted to test if i can connect to host wayland display
```
   Compiling env_logger v0.7.1
error: failed to run custom build command for `libdbus-sys v0.2.1`

Caused by:
  process didn't exit successfully: `/tmp/trizen-user/tiny-irc-client-git/src/tiny/target/release/build/libdbus-sys-896fa27fa9c525a5/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=DBUS_1_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=DBUS_1_STATIC
  cargo:rerun-if-env-changed=DBUS_1_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\" \"dbus-1 >= 1.6\"", cause: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libdbus-sys-0.2.1/build.rs:6:70
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tiny v0.7.0 (/tmp/trizen-user/tiny-irc-client-git/src/tiny/tiny)`, intermediate artifacts can be found at `/tmp/trizen-user/tiny-irc-client-git/src/tiny/target`

Caused by:
  build failed
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by osa1** [comment]
You need to install libdbus, as mentioned in the README.

**Comment by eoli3n** [comment]
Thanks, but ``dbus`` package provides ``libdbus`` and is already installed.

**Comment by eoli3n** [comment]
Finally, i get podman sandbox working, i wrote a gist : https://gist.github.com/eoli3n/93111f23dbb1233f2f00f460663f99e2
Rootless should work, but you need to enable dbus anonymous authentication on host to get it work, which is insecure.

Here the final procedure with a root container:
```
# Install docker or podman

# Prepare tiny config file
mkdir -p tiny-test/
cp ~/.config/tiny/config.yml tiny-test/

# Run an archlinux container with dbus and wayland sockets.
sudo podman run                                                    \
  --volume "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY":/tmp/wayland-0 \
  --volume (pwd)/tiny-test:/home/user/.config/tiny/  \
  --device /dev/dri                                           \
  --volume /run/user/1000/bus:/tmp/bus              \
  --rm -it archlinux /bin/bash

# In container, upgrade and install basic packages
pacman -Syu git fakeroot sudo binutils nano gcc cmake pkgconf libnotify imv --noconfirm

# Create a new sudo user, UID and GID should match you host user to make dbus work
useradd -m user && usermod -aG wheel user && chown -R user:user /home/user
echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Connect with user
su - user

# Connect wayland socket
export WAYLAND_DISPLAY=/tmp/wayland-0

# Connect dbus socket
export DBUS_SESSION_BUS_ADDRESS="unix:path=/tmp/bus"

# Test wayland backend
imv-wayland

# Test dbus
notify-send "Test"

# Install aur helper
git clone https://aur.archlinux.org/trizen.git && cd trizen && makepkg -si --noconfirm

# Install aur package
trizen -S tiny-irc-client-git
# It will prompt for editing files, add -p to mkdir command and change cargo command, save with C-x Maj-Y Enter

# Run tiny and ask for hl to notify your desktop
tiny
```
