### ISSUE TITLE
Freezing on startup on ArchWSL

### ISSUE THREAD

**Issue by LordMZTE** [osa1/tiny#269]
## Bug
When starting tiny on [ArchWSL](https://github.com/yuk7/ArchWSL) it will instantly freeze on startup no longer responding to any input.
I compiled it myself on the same system and there were no errors.

## Versions
tiny: Commit `4d3532`

**Comment by osa1** [comment]
4d3532 is the version that works, right? What is the version that hangs? One of the binaries in the releases page?

**Comment by LordMZTE** [comment]
`4d3532` is the version that hangs

**Comment by LordMZTE** [comment]
i cannot reproduce this issue on version `v0.7.0` but for some reason i always get `Connection error: failed to lookup address information: Temporary failure in name resolution` which is really confusing because when i ping the exact same address it works just fine

**Comment by osa1** [comment]
I'm a bit busy this week but I'll try to install ArchWSL and reproduce the issue.

In the meantime, if you have the time, it would be good to know (1) if you can connect to those servers on Linux or another WSL (2) if you have the freeze issue on other WSLs.

**Comment by LordMZTE** [comment]
i am able to reproduce both issues on ubuntu WSL

**Comment by osa1** [comment]
Do the issues exist in pre-built binaries in the release page? It'd be good if you could try with a libssl one and one without libssl.

**Comment by LordMZTE** [comment]
both prebuilt relases (libssl and without libssl) run just fine.
i previously installed with `cargo install --git https://github.com/osa1/tiny.git --tag v0.7.0` and got the before mentioned issues. any ideas why?

**Comment by osa1** [comment]
>  i previously installed with cargo install --git https://github.com/osa1/tiny.git --tag v0.7.0 and got the before mentioned issues. any ideas why?

Hmm, this is weird. If 0.7.0 worked fine (pre-built binaries and when you build from source) but current master branch didn't then I'd suspect it could be https://github.com/osa1/tiny/commit/4a55e47d81f2dcd88326035b515d8670e8992e46, but if 0.7.0 doesn't work when you build from source then I have no idea.

So if I understand this correctly when you build from source (version doesn't matter) it doesn't work but pre-built binaries work. That's really weird.

**Comment by LordMZTE** [comment]
when i build from the latest commit it freezes, when i build form 0.7.0 it doesn't connect and the prebuilt release works

**Comment by osa1** [comment]
This is introduced with 4a55e47. Here's what I tried:

- The last release works fine, both the pre-built binaries and when I build locally in Ubuntu WSL.
- Commits up to 4a55e47 also work fine when I build locally.
- With 4a55e47 the process hangs after about a second. It doesn't handle input events at all, but it seems to handle network events for about a second or so before freezing.

I wonder if this is a tokio bug. I should probably ask tokio devs first about any known issues on WSL.

**Comment by osa1** [comment]
Updating to tokio-0.3.4 doesn't fix the issue.

**Comment by osa1** [comment]
Example programs in term_input and termbox also hang. They don't use CPU when this happens.

**Comment by osa1** [comment]
echo_bot example in libtiny_tui works fine. "input" example in term_input only uses mio (no tokio) and it also doesn't work on WSL (works on Linux).

**Comment by LordMZTE** [comment]
Interesting! Do you have any guesses on why I was experiencing network problems when building from source but not on the prebuilt version?
- I believe I tried with both the nightly and stable compiler.
- Which version of Ubuntu WSL are you using? I tried on version 20.04.
- Could I have installed a dependency such as OpenSSL incorrectly?

**Comment by osa1** [comment]
> Do you have any guesses on why I was experiencing network problems when building from source but not on the prebuilt version?

I have no idea..

> Which version of Ubuntu WSL are you using? I tried on version 20.04.

I'll check this evening when I can switch to Windows.

> Could I have installed a dependency such as OpenSSL incorrectly?

Possible, but note that I tried with rustls and observed the problem. So it may not be related to OpenSSL.

---

Update to my previous comment: the "input" example uses term_input. I was confused because I didn't see it imported, but we use it as qualified, e.g. `term_input::Input::new()`.

So it is still possible that the problem is in `term_input`.

**Comment by LordMZTE** [comment]
It may not be related to the Ubuntu WSL version, as i got identical behaviour on ArchWSL

**Comment by osa1** [comment]
I fixed the issue locally (not pushed yet). Basically we need to set stdin fd to non-blocking mode otherwise `read()` blocks even in canonical mode. Interestingly, I had considered this case and did some research on this, and I found on Linux when in canonical mode you don't need to set stdin fd to non-blocking. I even documented it here: https://github.com/osa1/tiny/blob/997f6a808f88e4cf1072d16e5a9ac4d189a914b8/term_input/src/lib.rs#L8-L14

But apparently on WSL you need to set stdino to non-blocking mode even when you're in canonical mode. Not sure if this is a WSL bug or not ...

**Comment by LordMZTE** [comment]
Interestingly, I did use tiny on WSL (ubuntu 18) without issues but since then I reset my system and now I'm experiencing the before mentioned issues, so it could be that an update to WSL caused this given I get the same behaviour on ArchWSL and UbuntuWSL.
