### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by atommixz** [osa1/tiny#27]
Conection error (HUP). Will try to reconnect in 30 seconds.

Connection?

btw what's mean HUP?

**Comment by osa1** [comment]
`HUP` is the `PULLHUP` error thrown by poll() or multiplexing functions. From `man poll`

```
       POLLHUP     A  device  has  been disconnected, or a pipe or FIFO has been closed by the last process that had it open for writing.
                   Once set, the hangup state of a FIFO shall persist until some process opens the FIFO for writing or  until  all  read-
                   only  file  descriptors  for the FIFO are closed. This event and POLLOUT are mutually-exclusive; a stream can never be
                   writable if a hangup has occurred. However, this event and POLLIN, POLLRDNORM, POLLRDBAND, or POLLPRI  are  not  mutu-
                   ally-exclusive. This flag is only valid in the revents bitmask; it shall be ignored in the events member.
```

So this is not a typo. Re-open if I misunderstood this issue.

**Comment by DanielOaks** [comment]
I think the typo they're referring to is "Connection" accidentally being spelled as "Conection" [here](https://github.com/osa1/tiny/blob/93ba1cb3d0b291826f9f4b378ea6b3057077e1a1/src/lib.rs#L508) and [here](https://github.com/osa1/tiny/blob/93ba1cb3d0b291826f9f4b378ea6b3057077e1a1/src/lib.rs#L576)

**Comment by osa1** [comment]
Ah, right. Thanks. Just fixed it.
