### ISSUE TITLE
Tabs still change color for join/part even if /ignore is enabled

### ISSUE THREAD

**Issue by trevarj** [osa1/tiny#291]
Problem: when /ignore is enabled, tabs should not change color on the joining or parting of a user

This is my fault, I think. When I added the `JoinOrPart` tab style I didn't check this scenario.

It comes from these two identical lines in `conn.rs` :
```
ui.set_tab_style(TabStyle::JoinOrPart, &MsgTarget::Chan { serv, chan: &chan })
```
Doesn't look like there's a way to get the ignore from there without adding another function on `ui`, so you could probably change it here in `tui.rs`:
```
    pub(crate) fn set_tab_style(&mut self, style: TabStyle, target: &MsgTarget) {
        self.apply_to_target(target, &|tab: &mut Tab, is_active: bool| {
            if !is_active && tab.style < style {
                tab.set_style(style);
            }
        });
    }
```

**Comment by osa1** [comment]
Good catch @trevarj . I think you're right that `set_tab_style` is where we fix this.
