### ISSUE TITLE
Backspace doesn't work anymore

### ISSUE THREAD

**Issue by zserik** [osa1/tiny#295]
I pulled the current master (which I hadn't done for several months) and now just realized that I can't delete text via Backspace anymore. This is a bug. It worked in the past, althrough I can't name the exact commit I had previously checked out, which worked.

**Comment by zserik** [comment]
I gathered the following snippet via strace at/after backspace was pressed:
```
epoll_wait(3, [{EPOLLIN, {u32=1, u64=1}}], 1024, 28788) = 1
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
read(0, "\10", 100)                     = 1
read(0, "", 100)                        = 0
write(9, "\33[79;12H", 8)               = 8
epoll_wait(3, [{EPOLLIN, {u32=2147483648, u64=2147483648}}], 1024, 4759) = 1
epoll_wait(3, [], 1024, 4759)           = 0
```

**Comment by zserik** [comment]
found a way to fix it:
```patch
diff --git a/term_input/src/lib.rs b/term_input/src/lib.rs
index 7135ba3..ea27951 100644
--- a/term_input/src/lib.rs
+++ b/term_input/src/lib.rs
@@ -107,6 +107,7 @@ byte_seq_parser! {
     [27, 79, 70] => Key::End,
     [27, 91, 52, 126] => Key::End,
     [9] => Key::Tab,
+    [8] => Key::Backspace,
     [127] => Key::Backspace,
     [1] => Key::Ctrl('a'),
     [5] => Key::Ctrl('e'),
```

**Comment by osa1** [comment]
Thanks for reporting @zserik . Which terminal are you using? I'd like to try this and find out why it got broken. I don't remember making any changes in `term_input` that might break this.
