### ISSUE TITLE
Tab characters not shown in TUI

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#305]
@Kabouik reported on IRC that tiny doesn't show tab characters. Haven't check the code yet but I wouldn't be surprised if we just completely ignore tab characters in termbox.

**Comment by Kabouik** [comment]
Thanks for opening the issue @osa1. To illustrate the issue, if I use `$EDITOR` (Kakoune in my case)  to post this in Tiny:

```
<div>
	<p>
		aaa
	</p>
	<p>
		bbb
	</p>
</div>

<div>
    <p>
        Let's see if it's related to my editor using \t instead of spaces.
    </p>
</div>
```

I get this:
![Screenshot_20210205_003](https://user-images.githubusercontent.com/7107523/107083313-b9653c00-67f5-11eb-840e-1542a4a55fea.png)

And it seems others using other clients see the indentation even when I use only tabs, but they didn't tell me which client they were using. @sarnold in the #tiny channel showed that `irssi` users see that:

```
irssi in tmux in mosh in urxvt. The capital Is are inverse video tabs.

Fri 05 14:58:53 < Kabouik> <div>
Fri 05 14:58:53 < Kabouik> I<p>
Fri 05 14:58:53 < Kabouik> IIaaa
Fri 05 14:58:55 < Kabouik> I</p>
Fri 05 14:58:55 < Kabouik> I<p>
Fri 05 14:58:57 < Kabouik> IIbbb
Fri 05 14:58:57 < Kabouik> I</p>
Fri 05 14:58:59 < Kabouik> </div>
Fri 05 14:58:59 < Kabouik>  
Fri 05 14:59:01 < Kabouik> <div>
Fri 05 14:59:01 < Kabouik>     <p>
Fri 05 14:59:03 < Kabouik>         Let's see if it's related to my editor using \t instead of spaces.
Fri 05 14:59:03 < Kabouik>     </p>
Fri 05 14:59:05 < Kabouik> </div>
Fri 05 14:59:33 < Kabouik> Yeah, I can see space-identation, not tab-identation
Fri 05 14:59:48 < Kabouik> But apparently others using other IRC clients could see tab-identation too
```

**Comment by osa1** [comment]
termbox's tab handling is fine. Here's an example:

```rust
use term_input::{Event, Input, Key};
use termbox_simple::*;
use tokio::stream::StreamExt;

fn main() {
    let mut tui = Termbox::init().unwrap();

    draw(&mut tui);

    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap();
    let local = tokio::task::LocalSet::new();

    local.block_on(&runtime, async move {
        let mut input = Input::new();
        while let Some(mb_ev) = input.next().await {
            match mb_ev {
                Err(_) => {}
                Ok(Event::Key(Key::Esc)) => {
                    return;
                }
                Ok(_) => {}
            }
            draw(&mut tui);
        }
    });
}

fn draw(tui: &mut Termbox) {
    tui.clear();

    tui.change_cell(0, 0, '\t', 0, 1);
    tui.change_cell(1, 0, 'x', 0, 1);

    tui.present();
}
```

When I run this I see

```
        x
```

so the tab is rendered as 8 spaces.

**Comment by osa1** [comment]
This must be where we drop the tab character, as it's considered a "control" character: https://github.com/osa1/tiny/blob/e82046a7530e8162a785a79f53d838ba22dc6b66/libtiny_tui/src/utils.rs#L92-L135

**Comment by osa1** [comment]
Fixed.

Note that we don't handle entering wide characters (characters that take more than one row on screen, e.g. `Ｈ`) in the input widget yet. I'll create another issue for that.

**Comment by osa1** [comment]
> Note that we don't handle entering wide characters (characters that take more than one row on screen, e.g. Ｈ) in the input widget yet. I'll create another issue for that.

Tracked in #306.
