### ISSUE TITLE
Right align nicknames, left align text?

### ISSUE THREAD

**Issue by 097115** [osa1/tiny#308]
Just a suggestion: what if `tiny` would have nicknames right-aligned, while the text left-aligned and also wrapped with some indent? Here's a pic:

![](https://i.imgur.com/iij8DCq.png)

It would additionally separate nicknames from the chat, and thus would make reading the chat easier... What do you think?

**Comment by osa1** [comment]
This was requested many times before, and it's currently being implemented by @trevarj in #301. You can see a screenshot in #299.

**Comment by 097115** [comment]
@osa1 Thanks so much for pointing this out. Will try ASAP. Feel free to close this issue if needed

:)

**Comment by trevarj** [comment]
This can be closed since it was added in #301
