### ISSUE TITLE
$$* in the tab line

### ISSUE THREAD

**Issue by eoli3n** [osa1/tiny#312]
![tab](https://user-images.githubusercontent.com/14223657/112516652-c800b600-8d97-11eb-84fb-eaf6c713ed79.png)

What is that ``$$*`` in the tab line ?

**Comment by osa1** [comment]
Is the tab contents `We'll be systematically restarting all of the servers on the network shortly in response to the recently published OpenSSL CVE. Please don't reconnect until you are disconnected. Sorry for any inconvenience this might cause!` ? If yes, then you're using an old version of tiny and you should update.

`$$*` is a wildcard for sending a message to all users. We didn't handle it correctly in the older versions.

**Comment by osa1** [comment]
The commit that fixed this is cae4666f1b49913b6c197571ab786380cb6972df, which is released with 0.8.0.

**Comment by eoli3n** [comment]
Problem is that i don't know how to open that tab, no char is underlined

**Comment by osa1** [comment]
You can switch tabs with C-n and C-p.

**Comment by eoli3n** [comment]
Learned something :) Thanks, it contains the string you said
