### ISSUE TITLE
Malformed USER command on empty realname

### ISSUE THREAD

**Issue by Halkcyon** [osa1/tiny#314]
https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#USER

When attempting to connect to freenode, if the `realname` configuration is set to an empty string, freenode responds that USER does not have enough parameters.  This is regardless of whether you are registered or SASL authentication succeeded.

I couldn't find whether this is invalid in the specification; it only calls out that names can contain spaces.

https://tools.ietf.org/html/rfc2812#section-3.1.3

https://github.com/osa1/tiny/blob/b61efc8e89a4e9fb6b4d54044c86a62f48fe139b/crates/libtiny_wire/src/lib.rs#L24-L26

**Comment by trevarj** [comment]
I think the realname is mandatory:

> In addition to the nickname, all servers must have the following information about all clients: The real name/address of the host that the client is connecting from, the username of the client on that host, and the server to which the client is connected.

https://modern.ircdocs.horse/#clients

**Comment by Halkcyon** [comment]
@trevarj if that is the case, I think it's a good idea to encode it as an error when parsing configuration to avoid invalid states?

**Comment by osa1** [comment]
Thanks for reporting. I also can't see whether `realname` can be empty, but apparently not. Unfortunately IRC is very poorly specified so often the answer to such questions is "whatever widely used servers do".

We also don't check for empty nicks. I guess we could add some validation to the config after parsing.
