### ISSUE TITLE
Aligned UI Changes 

### ISSUE THREAD

**Issue by trevarj** [osa1/tiny#316]
- ~~Make max_nick_length an optional config when Aligned when set https://github.com/osa1/tiny/pull/301#discussion_r613436001~~ Done in ebc620093459f4f8a7520fdb153883fe6225f087

- ~~Should we rename this to `Layout` maybe? (both the type name and the config field name) (config.rs line 32) https://github.com/osa1/tiny/pull/301#discussion_r613436319~~ Done in 87652bf55dd6507efb033dabca4f3d5589fdcea5

- ~~messaging.rs line 59 https://github.com/osa1/tiny/pull/301#discussion_r613441552~~ Done in c8dc19cc8136c9ee8e8ae7910d829e5a7d543129

_Originally posted by @osa1 in https://github.com/osa1/tiny/pull/301#discussion_r613436319_

**Comment by osa1** [comment]
All done, closing.

**Comment by trevarj** [comment]
Thanks 🙂
