### ISSUE TITLE
/msg nick pattern error

### ISSUE THREAD

**Issue by trevarj** [osa1/tiny#324]
Reported on IRC:

> using /msg *status znc_help gives a tiny error msg. i think the pattern matched
> for /msg needs to change to support *status

It appears that we don't match on '*' for the nickname in /msg
```
pub(crate) fn is_nick_first_char(c: char) -> bool {
    c.is_alphabetic() || "[]\\`_^{|}".contains(c)
}
```

**Comment by osa1** [comment]
According to RFC 2812 nicks can't start with `*`. The code you quoted implements nicks as described in RFC 2812.

That said, I think it's fine to just reject `#` as the first character (as `/msg` is for PRIVMSGs to users, not channels) and accept everything else.

We could also repurpose `/msg` to allow sending to channels too. I don't remember why I wanted to disallow channel names in `/msg`.

I suggest we do the former for now and allow everything except `#` as the first char.
