### ISSUE TITLE
input_delete_to_start

### ISSUE THREAD

**Issue by eoli3n** [osa1/tiny#332]
As seen in https://github.com/osa1/tiny/pull/328, there is no function to emulate term ``C-u``
Maybe duplicate of https://github.com/osa1/tiny/issues/300 ?

**Comment by osa1** [comment]
#382 is merged and we now have a `input_delete_to_end` action. Perhaps we can also implement this. @trevarj do you see any problems with this? It's fine if by default we don't have a binding for it.

**Comment by trevarj** [comment]
It should be an easy addition. I will have a look later
