### ISSUE TITLE
libressl support?

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#37]
aeosynth reported on /r/rust that [Void Linux](https://www.voidlinux.eu/) uses LibreSSL and so tiny doesn't work on that platform. It seems like we don't have LibreSSL bindings for Rust yet so I think (unless LibreSSL is ABI compatible with OpenSSL) the best we can do is to add a compile-time flag to disable TLS features.

**Comment by aeosynth** [comment]
I just needed to install the headers, then tiny install worked.

**Comment by osa1** [comment]
Thanks all. I added a few words to README about this.
