### ISSUE TITLE
[feature request] move right/left a buffer in the bufferlist

### ISSUE THREAD

**Issue by eoli3n** [osa1/tiny#381]
It would be great, when opening a lot of buffers, to be able to group some by moving them close to the others

**Comment by osa1** [comment]
You can move tabs around with alt+left/right arrow. Have you tried that? Is this different than moving tabs with alt+left/right arrow?

**Comment by eoli3n** [comment]
I want to move, not switch.
Alt+left/right == Alt+left/right.
If you meant ``ctrl`` it doesn't work too.

**Comment by osa1** [comment]
Maybe I misunderstand what you're asking, but `alt+arrow` *moves* the tab, does not change selected tab. See the recording below.

Are you using tmux? If you are, I'm guessing it may not be passing alt+arrow keys as expected to the shell.

Below I'm reversing the order of channel tabs with `alt+arrow` keys.

![Peek 2022-02-04 13-54](https://user-images.githubusercontent.com/448274/152517155-d5bbbbbf-613f-4d0b-98bf-3edb632694c2.gif)

**Comment by eoli3n** [comment]
I had ``alt_right:  tab_next`` as a custom keybind in my config, that's why !
