### ISSUE TITLE
hide join/leave messages?

### ISSUE THREAD

**Issue by ahillio** [osa1/tiny#392]
Is there a way to hide the messages/notices that indicate a user joining/leaving the channels?  If not... would you consider adding that ability?

**Comment by trevarj** [comment]
`/ignore` in the channel that you want to turn join/parts off

**Comment by ahillio** [comment]
omg thanks!!!

Can that be done by default / automatically via the `config.yml`?

**Comment by trevarj** [comment]
@ahillio only on this branch: https://github.com/trevarj/tiny/commits/experimental

See: https://github.com/osa1/tiny/pull/344

**Comment by ahillio** [comment]
oh great! thanks!!!
