### ISSUE TITLE
Use variables to indicate where the certificate is.

### ISSUE THREAD

**Issue by marshallishere** [osa1/tiny#399]
Hey, I was adding a certificate to my tiny config and I would like to set as follow:
`pem: "$XDG_CONFIG_HOME/tiny/certs/cert.pem"`
But it doesn't seems to work. I do have this variable setted and the path is correct.

**Comment by trevarj** [comment]
tiny doesn't don't do any resolution of the shell environment when parsing the config file (only when looking for the config file), so you will need to write the path without `$XDG_CONFIG_HOME` (i.e `~/.config/tiny/certs/cert.pem`)
