### ISSUE TITLE
Show NickServ messages in server tabs

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#4]
I think most users would have something like
```
- msg NickServ identify hunter2
```

as an auto cmd in .tiny.yml. It's slightly annoying that this command creates a new private message tab to show messages sent to/received from NickServ after every time connection is established, but that tab is never actually used because no one really chats with NickServ. So maybe we should implement a special case for sending messages to NickServ to show those messages (and responses) in server tabs.

**Comment by FreeFull** [comment]
An alternative could be a flag for /msg which prevents a tab from opening.
