### ISSUE TITLE
del key inserts a ~3 instead of deleting

### ISSUE THREAD

**Issue by saethlin** [osa1/tiny#41]
Is this a result of the input library?

**Comment by osa1** [comment]
> Is this a result of the input library?

Correct. In addition, becuase `del` key was never caught by the input library, tiny has no support to handle that key. So both `term_input` and `tiny` need to be updated.

If anyone wants to contribute, this seems like a great task for new contributors:

- Add a new `Del` key in term_input.
- Map byte string `[ 27, 91, 80 ]` to to `Del`
- Test it with `cd term_input; cargo run --example test` and `cd termbox; cargo run --example input`, make sure both show `Del` when pressed the del key.
- Update tiny's key handler to handle the new `Del` key (just add a new case to `TextField::keypressed`. Just look at the code for `Key::Backspace` and adapt it for deleting the character under the cursor.

Would anyone want to give this a try? (ping @meain @BrianOn99 )

**Comment by BrianOn99** [comment]
I would like to fix this.  And thanks for the detailed guide!
