### ISSUE TITLE
Panics in msg_area and client

### ISSUE THREAD

**Issue by wezm** [osa1/tiny#415]
Sorry this a little intermixed with the UI.

```
wezm: thread 'main' panicked at 'Out of bounds access', crates/libtiny_tui/src/msg_area/mod.rs:223:16ns irc.libera.chat #lobsters irc.oftc.net #chimera-linux
      note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                                                                   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', crates/libtiny_client/      b.rs:528:76
```

There appears to be two panics in here:

1. https://github.com/osa1/tiny/blob/c512887af7b4b89f451fdc75216fd2e659fd1ec3/crates/libtiny_tui/src/msg_area/mod.rs#L223
2. https://github.com/osa1/tiny/blob/c512887af7b4b89f451fdc75216fd2e659fd1ec3/crates/libtiny_client/src/lib.rs#L528

I can't reliably reproduce this but it has happened multiple times. I leave `tiny` running and suspend and resume my machine. Normally when resuming it reconnects fine but occasionally it panics. I think in the case above I also ran `/clear` after it reconnected (I do this fairly commonly and it doesn't always panic)

Additionally when I exited (via Ctrl+c y) I got another panic:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Closed(..)"', crates/libtiny_client/src/lib.rs:258:51
```

https://github.com/osa1/tiny/blob/c512887af7b4b89f451fdc75216fd2e659fd1ec3/crates/libtiny_client/src/lib.rs#L258

### System Info

**OS:** Arch Linux
**Tiny Version:** 0.11.0 (installed [via AUR](https://aur.archlinux.org/packages/tiny-irc-client) package with version manually bumped up to 0.11)
**Terminal:** Alacritty
**Window Manager:** Awesome

**Comment by osa1** [comment]
Thanks for reporting. I'm not sure how to debug this, but I think we should start by updating tokio and getting the latest bug fixes. I will do that and report back.

**Comment by osa1** [comment]
I looked at the error message in more detail and I think it's probably a bug in the TUI. Since you said it happened multiple times, would it be possible to run tiny (current master branch) in debug mode and share the full backtrace?

**Comment by osa1** [comment]
@wezm how often are you using `/clear`? I fixed  bug with `/clear` in #417 which I think may be related. I'll try to merge it today.

**Comment by osa1** [comment]
I just merged #417. If you're seeing this crash after a `/clear` then the bug should be fixed. If you don't use `/clear` at all then the bug probably still exists and it would be helpful if you could run a debug build using the current master branch and share the full backtrace.

**Comment by wezm** [comment]
I use /clear about once a day, usually after tiny reconnects. I'll try running a debug master build anyway and see how it goes. Thanks for looking into it.

**Comment by osa1** [comment]
> I use /clear about once a day, usually after tiny reconnects

In that case I'm pretty sure I fixed the right bug. I'll close this as fixed.

**Comment by wezm** [comment]
I've been running a master build all week and so far have not encountered any issues so I think you're right that #417 has fixed it.

**Comment by osa1** [comment]
Thanks for confirming!
