### ISSUE TITLE
"Can't parse TUI config:" Error

### ISSUE THREAD

**Issue by sfalken** [osa1/tiny#425]
I'm not entirely certain what I'm supposed to do to fix this error:

```
Can't parse TUI config: Message("invalid type: sequence, expected string or map", Some(Pos { marker: Marker { index: 55, line: 3, col: 10 }, path: 
"servers[0]" }))
```  

I assume it's something that I've done incorrectly in my config.yml, but looking at line 3, it just consists of:
`- addr: irc.libera.chat`   

Column 10 being the `r` in `addr`  

Can someone point me at what I'm doing wrong here?

I've attached a sanitized version of my config, just in case that helps.
[config.txt](https://github.com/osa1/tiny/files/13795695/config.txt)

**Comment by osa1** [comment]
What's the output of `tiny --version`? I can run with your config file using tiny master branch.

**Comment by sfalken** [comment]
0.11.0

**Comment by osa1** [comment]
It looks like this line causes a problem with 0.11.0:
```
notify: [mentions]
```
It should be
```
notify: mentions
```
However I don't understand why the master version accepts it without any errors. I will take a look.

**Comment by osa1** [comment]
Ah, I think I tested this incorrectly, master version also fails to parse the config because of the same issue.

**Comment by sfalken** [comment]
Thanks for the help, cleared it up here just fine.
