### ISSUE TITLE
smarter substring mach for highlighting

### ISSUE THREAD

**Issue by gabevenberg** [osa1/tiny#430]
My nick, 'toric', is found as a substring in the word 'historic', 'historical', etc. Needless to say, this causes quite a few errant messages in the mentions tab, due to the current implementation looking for any substring match. Perhaps a regex utilizing word boundaries, like `\b{}\b`, would be better?

**Comment by osa1** [comment]
Good idea. I'm surprised that we don't do this already, and that this wasn't reported before.

I generally try to avoid regexes but I think it's OK in this case (we already depend on the `regex` crate via the `zbus` dependency). However we can't use `\b` for the boundaries as that won't include valid nicks like `osa1_`. This is a common case: some clients, including tiny, add `_` suffix to the nick when it's in use.

We should follow the nick syntax specification here: https://modern.ircdocs.horse/#clients.

So the regex should be something like: `(?:^|[ ,*?!@&:#+~])myNick(?:$|[ ,*?!@.])` (replace `myNick` with the user's nick).

I.e. the user's nick, sandwiched by an invalid start character (or beginning of the string) on the left and an invalid non-start character (or end of the string) on the right.

The regex should be compiled once and should be recompiled as the user's nick change.
