### ISSUE TITLE
Weird Highlighting

### ISSUE THREAD

**Issue by znschaffer** [osa1/tiny#434]
my nick is znschaffer yet tiny keeps on highlighting YouTube links bizarrely.

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/ecc15fe4-f703-437a-a564-625322bc5ed0">

I'm not sure what in the regex for nick's would cause this but it's mighty annoying

**Comment by osa1** [comment]
This is probably an IRC color code to show the "Tube" part in red background, similar to the old logos here: https://logos-world.net/youtube-logo/ (scroll to "Meaning and History").

It looks like either the colored part is not terminated, or it is terminated but we don't handle the termination code properly.

Have you checked if these messages look as expected in other clients?

Which server/channel is this? Maybe I (or someone else) can join and debug this.

**Comment by osa1** [comment]
@znschaffer could you try #435 and let me know if it fixes the issue?

**Comment by znschaffer** [comment]
oh my! i never would've thought it was added in w/ escape codes to replicate the old logomark. trying this patch now

**Comment by znschaffer** [comment]
<img width="800" alt="image" src="https://github.com/user-attachments/assets/44af2e64-ee98-48f2-a9cf-44e2816bdb37">
cheers! @osa1

**Comment by osa1** [comment]
That's better, but it still doesn't look right. The part after "Tube" looks bold now. Is this expected? Is it how it looks like in other clients?
