### ISSUE TITLE
reproducible builds problem

### ISSUE THREAD

**Issue by bmwiedemann** [osa1/tiny#437]
While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds) (sponsored by the NLnet NGI0 fund), I found that
our `tiny` package varies in every build.

Another developer pointed at HashMaps in
https://github.com/osa1/tiny/blob/ee8615a55256b242b02e6f8a2350ca7f39aca517/crates/term_input_macros/src/tree.rs#L6
with non-deterministic iteration order.

Maybe it could be replaced with [indexmap](https://github.com/indexmap-rs/indexmap), [ordermap](https://github.com/indexmap-rs/ordermap) or something else...

**Comment by osa1** [comment]
Thanks for reporting this. You were right that the hash map in the macro was the cause. I've updated it to `IndexMap` and made 10 builds and they were all identical, so the issue should be fixed. Please re-open if it isn't.
