### ISSUE TITLE
tiny floods server on reconnect when joined too many channels

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#49]
This is because we send `join` messages twice for each channel.

1. We run `auto_cmds` on reconnect which includes `/join` commands
2. `Conn` sends a `join` message for each channel that we had joined before disconnecting.

So we end up sending two `join` messages for each channel. With 11 channels freenode considers this as flood.

It seems to me that we should add two new fields to the config:

1. `auth` for authentication commands (see #30)
2. `join` for channels to automatically join

With this we run `auth` on after connecting (including after losing the connection and reconnecting), and `join` only on connecting for the first time (so no `join` after losing the connection and reconnecting again).

Any `auto_cmds` or `join` commands will be run after `auth`. `Conn` then rejoins the channels as usual.

This also fixes #30 and #38.

**Comment by FreeFull** [comment]
You can join several channels with a single JOIN, by separating their names with commas.

**Comment by osa1** [comment]
> You can join several channels with a single JOIN, by separating their names with commas.

Yep, just implemented this as well.
