### ISSUE TITLE
Dependencies are not on crates.io

### ISSUE THREAD

**Issue by ivanceras** [osa1/tiny#6]
It seems like you've included a dependencies that is relative to your project files.
```
ev_loop = { path = "ev_loop/" }
term_input = { path = "term_input/" }
termbox_simple = { path = "termbox/" }
```
Do you mind publishing or using a version in crates.io?
I can't build this project on my macbook. It's strange that travi-ci built this without problem.

**Comment by ivanceras** [comment]
cargo build
   Compiling ev_loop v0.1.0 (file:///Users/lee/playground/tiny/ev_loop)
   Compiling termbox_simple v0.1.0 (file:///Users/lee/playground/tiny/termbox)
   Compiling nix v0.7.0
error[E0425]: cannot find value `CLOCK_MONOTONIC` in module `libc`
   --> ev_loop/src/lib.rs:116:48
    |
116 |         let fd = unsafe { timerfd_create(libc::CLOCK_MONOTONIC, libc::EFD_NONBLOCK) };
    |                                                ^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `EFD_NONBLOCK` in module `libc`
   --> ev_loop/src/lib.rs:116:71
    |
116 |         let fd = unsafe { timerfd_create(libc::CLOCK_MONOTONIC, libc::EFD_NONBLOCK) };
    |                                                                       ^^^^^^^^^^^^ did you mean `O_NONBLOCK`?

error[E0425]: cannot find function `signalfd` in module `libc`
   --> ev_loop/src/lib.rs:136:33
    |
136 |         let fd = unsafe { libc::signalfd(-1, sigs, libc::EFD_NONBLOCK) };
    |                                 ^^^^^^^^ did you mean `signal`?

error[E0425]: cannot find value `EFD_NONBLOCK` in module `libc`
   --> ev_loop/src/lib.rs:136:58
    |
136 |         let fd = unsafe { libc::signalfd(-1, sigs, libc::EFD_NONBLOCK) };
    |                                                          ^^^^^^^^^^^^ did you mean `O_NONBLOCK`?

error[E0412]: cannot find type `signalfd_siginfo` in module `libc`
   --> ev_loop/src/lib.rs:183:56
    |
183 |                                 let mut siginfo: libc::signalfd_siginfo = unsafe { std::mem::zeroed() };
    |                                                        ^^^^^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `signalfd_siginfo` in module `libc`
   --> ev_loop/src/lib.rs:187:68
    |
187 |                                         &mut siginfo as *mut libc::signalfd_siginfo as *mut libc::c_void,
    |                                                                    ^^^^^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `signalfd_siginfo` in module `libc`
   --> ev_loop/src/lib.rs:188:67
    |
188 |                                         std::mem::size_of::<libc::signalfd_siginfo>())
    |                                                                   ^^^^^^^^^^^^^^^^ not found in `libc`

error[E0308]: mismatched types
   --> ev_loop/src/lib.rs:162:59
    |
162 |             assert!(unsafe { libc::poll(fds.as_mut_ptr(), fds.len() as u64, -1) } != -1);
    |                                                           ^^^^^^^^^^^^^^^^ expected u32, found u64
    |
    = help: here are some functions which might fulfill your needs:
            - .count_ones()
            - .count_zeros()
            - .leading_zeros()
            - .trailing_zeros()

error: aborting due to previous error(s)


I noticed that those dependencies are in the project directory, my bad.

However, when building the project it has errors.

```
cargo build
   Compiling ev_loop v0.1.0 (file:///Users/my/playground/tiny/ev_loop)
   Compiling term_input v0.1.0 (file:///Users/my/playground/tiny/term_input)
error[E0425]: cannot find value `CLOCK_MONOTONIC` in module `libc`
   --> ev_loop/src/lib.rs:116:48
    |
116 |         let fd = unsafe { timerfd_create(libc::CLOCK_MONOTONIC, libc::EFD_NONBLOCK) };
    |                                                ^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `EFD_NONBLOCK` in module `libc`
   --> ev_loop/src/lib.rs:116:71
    |
116 |         let fd = unsafe { timerfd_create(libc::CLOCK_MONOTONIC, libc::EFD_NONBLOCK) };
    |                                                                       ^^^^^^^^^^^^ did you mean `O_NONBLOCK`?

error[E0425]: cannot find function `signalfd` in module `libc`
   --> ev_loop/src/lib.rs:136:33
    |
136 |         let fd = unsafe { libc::signalfd(-1, sigs, libc::EFD_NONBLOCK) };
    |                                 ^^^^^^^^ did you mean `signal`?

error[E0425]: cannot find value `EFD_NONBLOCK` in module `libc`
   --> ev_loop/src/lib.rs:136:58
    |
136 |         let fd = unsafe { libc::signalfd(-1, sigs, libc::EFD_NONBLOCK) };
    |                                                          ^^^^^^^^^^^^ did you mean `O_NONBLOCK`?

error[E0412]: cannot find type `signalfd_siginfo` in module `libc`
   --> ev_loop/src/lib.rs:183:56
    |
183 |                                 let mut siginfo: libc::signalfd_siginfo = unsafe { std::mem::zeroed() };
    |                                                        ^^^^^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `signalfd_siginfo` in module `libc`
   --> ev_loop/src/lib.rs:187:68
    |
187 |                                         &mut siginfo as *mut libc::signalfd_siginfo as *mut libc::c_void,
    |                                                                    ^^^^^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `signalfd_siginfo` in module `libc`
   --> ev_loop/src/lib.rs:188:67
    |
188 |                                         std::mem::size_of::<libc::signalfd_siginfo>())
    |                                                                   ^^^^^^^^^^^^^^^^ not found in `libc`

error[E0308]: mismatched types
   --> ev_loop/src/lib.rs:162:59
    |
162 |             assert!(unsafe { libc::poll(fds.as_mut_ptr(), fds.len() as u64, -1) } != -1);
    |                                                           ^^^^^^^^^^^^^^^^ expected u32, found u64
    |
    = help: here are some functions which might fulfill your needs:
            - .count_ones()
            - .count_zeros()
            - .leading_zeros()
            - .trailing_zeros()

error: aborting due to previous error(s)

error: Could not compile `ev_loop`.
Build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by osa1** [comment]
Hey, thanks for reporting.

> Do you mind publishing or using a version in crates.io?

I didn't want to push on crates.io because:

- Some of those really make sense in this project. For example, `ev_loop` is not intended to be reusable or even a well-designed event loop. It just something that works fine for this project.

- They will pollute crates.io namespace

- tiny is in early stages of development and sometimes those dependencies change too rapidly because of that. Publishing multiple crates every time would be painful.

Still I agree that tiny should be installable from crates.io so I'll find a way, it may just take some time.

> However, when building the project it has errors.

As I mentioned in the README, tiny has been developed and used on Linux and I haven't tried it on any other platform. It seems from your compiler output that only the `ev_loop` library needs porting (which is actually very small 214 lines if you ignore tests). Would you be interested in doing this yourself? I don't have a Mac so I'm not sure how to help with this.

**Comment by osa1** [comment]
Hey @ivanceras , I just landed OSX support. Could you try rebuilding tiny on your system and let me know if it works?

**Comment by ivanceras** [comment]
Hi @osa1. Yes was able to build and run in OSX.
