### ISSUE TITLE
make tiny znc friendly

### ISSUE THREAD

**Issue by DirectorX** [osa1/tiny#60]
make tiny [znc](/znc/znc) friendly

**Comment by osa1** [comment]
Hi @DirectorX ,

Could you try again with the latest version from git? It seems like the simple change I made with ef32f05 is enough to connect to znc.

To enter your password send `PASS user:pass` in the server tab. This currently needs to be done manually until we figure something out for sending znc passwords.

**Comment by DirectorX** [comment]
well done my friend

**Comment by osa1** [comment]
@DirectorX just pushed support for `PASS` command as well, so you can automatically send your password to znc now. Either add a `pass` field in your server configuration, or use `/connect znc_ip:znc_port your_password` to connect. Here's how my config looks like:

```
    - addr: localhost
      port: 10234
      tls: false
      hostname: omer
      realname: omer
      nicks: [osa1]
      auto_cmds: []
      pass: 'my_zns_user:my_znc_pass'
```

**Comment by DirectorX** [comment]
all done, im ready to drop irssi
