### ISSUE TITLE
Unhandled EWOULDBLOCK errors breaking TlsStream

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#64]
Originally reported by @reading123 on #61,

It seems like some `EWOULDBLOCK` errors are slipping through our error handlers and causing `Conn` methods to fail. The error message tiny prints is:

```
Connection error: The underlying stream reported an error (operation would block)
```

I can't reproduce this so I'm not sure how to solve. As a starting point we should probably compare our `EWOULDBLOCK` handling with tokio-core's TcpStream https://github.com/tokio-rs/tokio-core/blob/master/src/net/tcp.rs . 

I also created the issue https://github.com/sfackler/rust-native-tls/issues/63 but later it occured to me that if we do `EWOULDBLOCK` in `stream::tcp::TcpStream` we may not need any support from `native_tls`.

**Comment by osa1** [comment]
I can reproduce this reliably (as in, it never works) when I compile tiny with statically linked openssl-1.1.0g.

**Comment by reading123** [comment]
Yay it works!! No errors here.

**Comment by reading123** [comment]
Also, Merry Christmas! :)

**Comment by osa1** [comment]
Good to hear. Merry Christmas to you too :)
