### ISSUE TITLE
Add tiny to the AUR

### ISSUE THREAD

**Issue by spease** [osa1/tiny#73]
Just about to try this - would be nice if it were in the AUR instead of just a misc package.

**Comment by osa1** [comment]
I'm not an Arch user myself, paging @wrycode @BrianOn99 who are Arch users AFAIK.

**Comment by BrianOn99** [comment]
@spease We have a PKGBUILD [here](https://github.com/osa1/tiny/blob/master/pkg/archlinux/PKGBUILD), but seems it is not yet submitted to AUR.  @wrycode is it?

Any way if you want to try, just download the PKGBUILD and then `makepkg`.  Welcome!

**Comment by wrycode** [comment]
I am not quite ready to add it to the AUR. Once #65 is implemented there will be a "tiny" (vs "tiny-git") PKGBUILD to make as well, which will probably be a better solution for the average Arch user.

@BrianOn99 if you want to submit it before me, you are welcome to. I am waiting to check and double-check the different guidelines ([Arch Packaging Standards](https://wiki.archlinux.org/index.php/Arch_packaging_standards), [Rules of Submission](https://wiki.archlinux.org/index.php/Arch_User_Repository#Rules_of_submission)) before submitting it. That being said, the PKGBUILD works fine.
