### ISSUE TITLE
Ignore mode is disabled upon automatic reconnect

### ISSUE THREAD

**Issue by wrycode** [osa1/tiny#75]
After opening my laptop from sleep, Tiny detects that I've been disconnected after some time (I haven't tested it yet, but it seems like about 1 minute). Then after reconnecting, the "ignore" mode is no longer enabled, so I see the join/part messages in all channels.

**Comment by wrycode** [comment]
It appears that Tiny _does_ enable the ignore mode upon reconnecting, according to the server tab, but I still get the join/part messages in my channel tabs.

![screenshot_2018-01-05_16-57-42](https://user-images.githubusercontent.com/34693012/34630321-99749808-f239-11e7-86e2-ab44a0724407.png)

**Comment by osa1** [comment]
Paging @meain who implemented this feature. @meain let me know if you don't have time or anything.

I suspect this is because you have `ignore` in your `auto_cmds`. So on every reconnection it's toggled.

**Comment by meain** [comment]
Sure, I will take a look into this.

**Comment by meain** [comment]
I kinda got all lost in a lot of stuff. Getting out of college and landing my first job.  Sorry about that.

Could you give me some idea on what happens when tiny reconnects. I will see if I can get this fixed

**Comment by wrycode** [comment]
Yes that's correct, so this issue can probably be closed.

**Comment by meain** [comment]
@osa1 can't we close this issue?

**Comment by osa1** [comment]
Yeah, I think we can close this one. If needed we can open a new one to make it possible to set ignore state of a channel in the config file.
