### ISSUE TITLE
Change location of config file

### ISSUE THREAD

**Issue by wammies** [osa1/tiny#81]
It would be nice to be able to set a custom location for the `.tinyrc.yml` config file.

**Comment by osa1** [comment]
This would require passing a command line argument to tiny. Currently command line arguments are interpreted as server names to connect, so maybe we need a named flag for this.

**Comment by wammies** [comment]
I could have a go at this if you like - I'm pretty new to Rust, but I think I could figure it out.

**Comment by osa1** [comment]
> I could have a go at this if you like - I'm pretty new to Rust, but I think I could figure it out.

Sure. Let's add a named parameter `--config` for the config file path. All other parameters should be treated as server names as before. As for the library to choose, I've never done command line argument parsing in Rust so I don't know any of the libraries, but let's keep things simple and use the simplest one that works (even hand-rolling the parser might work if the implementation will be simpler than using a library).

Maybe create a new module with a type for command line arguments (something like `CmdLineArgs { servers: Vec<String>, config_path: Option<PathBuf> }`) and a parser. Then call the parser in `run()` (in `lib.rs`).

How does that sound?

**Comment by wammies** [comment]
Ok cool, that sounds good.
