### ISSUE TITLE
SASL authenication (request for comment)

### ISSUE THREAD

**Issue by BrianOn99** [osa1/tiny#90]
I have got SASL partially working, but before making a pull request there is one problem and I would ask for comment.

During the conservation of SASL (https://ircv3.net/specs/extensions/sasl-3.1.html), the client has to wait for server reply `:jaguar.test CAP jilles ACK :sasl`.  Not waiting for it sometimes work, but sometimes doesn't, so it is better to check it.  Is it reasonable to add a variant in `enum ConnStatus` for `waiting server ACK`?  I mean we will set this status and go back to `mainloop` without completing authenication, and look for server reply later.

**Comment by osa1** [comment]
> I have got SASL partially working

Awesome!

> the client has to wait for server reply :jaguar.test CAP jilles ACK :sasl

You mean before sending `AUTHENTICATE` messages, right? How about this:

- Send `CAP REQ :sasl` in `conn::introduce` before `NICK` and `USER` messages.
- Update `Conn::handle_msg` to send `AUTHENTICATE` messages after it reads an `ACK :sasl`.

So we'll wait for ACK before sending `AUTHENTICATE`, but without creating a new `ConnStatus`. I think this should be enough to get SASL running. Have you tried that?

**Comment by BrianOn99** [comment]
> Update Conn::handle_msg to send AUTHENTICATE messages after it reads an ACK :sasl

Looks nice.  I will try it out in the coming few days.
