### ISSUE TITLE
Feature: use an IRC library, or refactor IRC protocol logic out of tiny for consumption by others

### ISSUE THREAD

**Issue by dbkaplun** [osa1/tiny#94]

**Comment by osa1** [comment]
I'm curious, do you want this as a tiny user or a Rust developer? Why? If the latter, with this implemented, which part would you reuse, the protocol logic or the UI?

**Comment by Armavica** [comment]
I also looked some time ago for an IRC library (the protocol logic part). That seems to exist now: [aatxe/irc](https://github.com/aatxe/irc) seems relatively active and claims to be RFC-compliant and async-friendly.

It seems to me that these two projects would very well complement each other: as `tiny`'s readme mentions, "Only a small subset of IRC messages are implemented.", so perhaps leveraging this library could allow `tiny` to focus on the UI and avoid duplicating effort?

**Comment by osa1** [comment]
I'll write more about my plans on this but just to clarify

> It seems to me that these two projects would very well complement each other: as tiny's readme mentions, "Only a small subset of IRC messages are implemented.",

This TODO item is quite old and I should've actually remove it. These days you don't need any special support from tiny to send arbitrary commands to servers: any messages sent in a server tab are directly sent to the server. So for example to kick someone from a channel you could send `KICK ...` message in the server tab.

I now removed the TODOs section, pointing contributors to the issues.
