### ISSUE TITLE
channel name not handled properly (tui?)

### ISSUE THREAD

**Issue by DirectorX** [osa1/tiny#99]
**How to reproduce:**

join a channel
`/join #test`

then join with other client (no tiny) to that channel with uppercase letters
`/join #TesT`

send message in the second client

**what happened?:**

tiny create new channel window called `#TesT`

**Comment by osa1** [comment]
Thanks for reporting. This is indeed a tui bug. Fix incoming.

**Comment by osa1** [comment]
Sorry this took so long .. While I can see that we don't treat channel names as case insensitive in the UI, I can't reproduce this behavior because it seems like most servers treat channel names as case insensitive so when you try `/join #foo` but there's an existing channel `#FOO` they actually make you join `#FOO` instead.

May I ask which server you tried this on?

**Comment by osa1** [comment]
I just did this:

- Connected to irc.p2p-network.net with two instances of tiny.
- Created a channel `#FOO` with one of them.
- Joined `#foo` with the other

Result: Both clients are now in `#FOO`.

I also tried joining `#foo` with konversation, and it ended up joining `#FOO` instead, so again I didn't have any problems.

Which other IRC client did you use to reproduce this?

**Comment by DirectorX** [comment]
Hexchat

Jul 16, 2018, 4:00 PM by notifications@github.com:

**Comment by DirectorX** [comment]
you may also try to connect first with hexchat to `#TesT` then with tiny to `#test`

**Comment by osa1** [comment]
Still can't reproduce. Steps I took:

- Connect to p2p with hexchat
- Connect to p2p with tiny
- Join `#FoOo` with hexchat
- Join `#fooo` with tiny
- Send message from hexchat

tiny sees the message in the correct tab.

**Comment by DirectorX** [comment]
ok, i will try to reproduce this when i get home at the weekend.

Jul 16, 2018, 9:30 PM by notifications@github.com:

**Comment by DirectorX** [comment]
i just tried to reproduce, but i didn't managed to.

**Comment by osa1** [comment]
Alright, please reopen if you manage to reproduce.

**Comment by DirectorX** [comment]
its just happend in our private network. the client is `mIRC v7.29 Khaled Mardam-Bey` (that acts like notification bot). i dont have windows machine so i can't reproduce right now. i will update soon...
